### ISSUE TITLE
线程池监控

### ISSUE THREAD

**Issue by seaHeater** [alibaba/arthas#100]
有没有可能增加对线程池的监控，动态调整线程池配置

**Comment by ralf0131** [comment]
What exactly do you want to monitor of threadpool? Can you give some example?

For example,  ThreadPoolExecutor could have metrics like corePoolSize, maxKeepAliveTime.

In order to monitor the thread pool, you have to obtain the reference to the thread pool.

Without the reference you can't do anything.

Some commands like watch can obtain that reference when a method call comes in, if you could ensure that, you might be possible to monitor that.

```java

public class Test {
    private ThreadpoolExecutor threadpoolExecutor;  // init logic ignored

   public void test() {

   }

}
```

You can do something like this with Arthas:

```
watch Test test '{target.threadpoolExecutor.getCorePoolSize()}'
```

> Note that `target` means the reference to Test object, you can think of `this` keyword.

Every time test method get called, it will output the core size of thread pool.

Not sure if I've answered your question. Please give some feedback. :)

**Comment by seaHeater** [comment]
Thanks a lot, you've answered my question.
