### ISSUE TITLE
trace希望可以自定义记录调用的深度

### ISSUE THREAD

**Issue by hhxx1994** [alibaba/arthas#102]

**Comment by ralf0131** [comment]
Hi, 

`trace` an expensive command, and the feature you propose might be even more expensive.

Consider a method has to call 10 sub method, and each sub-method has to call 10 sub method. 

Arthas will have to instrument 10 * 10 = 100 methods in order to get the result. As it goes deeper, the  number of method to be instrumented will grow exponentially.

Besides, methods could be override, you even don't know which method be instrumented. The current approach is to instrument all the possible candidates.

This is why we don't implement that feature until we could find a better way to do that.

**Comment by ralf0131** [comment]
If someone could have a better idea to implement this feature, please let us know!

**Comment by Hearen** [comment]
@hhxx1994 @ralf0131 is right. If we recording all the invoked methods as what we do now, the amounts of records will increase exponentially. 

```
`---ts=2018-10-13 11:49:09;thread_name=Thread-1;id=d;is_daemon=false;priority=5;TCCL=sun.misc.Launcher$AppClassLoader@14dad5dc
    `---[0.725358ms] Demo:testListAdd()
        +---[0.013394ms] java.lang.StringBuilder:<init>()
        +---[0.010964ms] java.lang.Thread:currentThread()
        +---[0.007588ms] java.lang.Thread:getName()
        +---[min=0.00276ms,max=0.00962ms,total=0.01238ms,count=2] java.lang.StringBuilder:append()
        +---[0.006426ms] java.lang.StringBuilder:toString()
        +---[0.035918ms] java.io.PrintStream:println()
        +---[min=0.003342ms,max=0.010332ms,total=0.013674ms,count=2] java.util.ArrayList:<init>()
        +---[min=0.00284ms,max=0.0176ms,total=0.027166ms,count=4] java.util.List:add()
        `---[0.299372ms] Demo:addTwoLists()
```

But if we just care about the methods of our own, it can be dramatically reduced but is this what you are after?

**Comment by useraddZYB** [comment]
> If someone could have a better idea to implement this feature, please let us know!

因为arthas的粒度太细（每一行代码）或太粗（方法入参出参），合适的粒度应该是用户自定义的代码片段，我的实现方法可以做到trace接口下完整的方法链路，且通过埋点自定义代码片段长度：
https://github.com/useraddZYB/time-tracker

埋点虽然侵入性，但是能够解决问题；反过来，一个方案不能解决用户问题，实现的再优雅有什么用呢

**Comment by xuzhiyiYoh** [comment]
我也一直在想能不能实现一次trace到从api入口到所有业务方法的执行，这个在排查问题中很重要。
现在查问题为了找到调用路径，经常先trace A，再根据情况watch B, 再找到应该trace的 C.... 有点费劲
