### ISSUE TITLE
How to use on production env.

### ISSUE THREAD

**Issue by BarryIsIronMan** [alibaba/arthas#137]
I wanna ask how to use and deploy on production environment , if I deploy Arthas on every machine,how to attach them via website?

regards
Barry

**Comment by ralf0131** [comment]
Currently you have to login to the machine, install it, and run as.sh to attach.

If you are using docker, you can add Arthas into your docker image, so that you don't bother install it every time.

If you want to attach it remotely, you have ask help for another system that can accept your request, and execute as.sh for you. This normally works like a daemon in your system.
