### ISSUE TITLE
无法选中目标进程，总是进入第一个进程

### ISSUE THREAD

**Issue by youdianwuliao** [alibaba/arthas#161]
试了多次还是不行，总是选中第一个，咋回事啊？那块操作不对啊

**Comment by hengyunabc** [comment]
要输入具体的数字，再按enter。 或者 `bash -x ./as.sh` 调试下

**Comment by liukeyu** [comment]
遇到相似的问题，总共两个进程
Arthas script version: 3.0.4
Found existing java process, please choose one and hit RETURN.
* [1]: 10310 ServerStartup
  [2]: 32391 ClientMain
**1**
Calculating attach execution time...
Attaching to 10310 using version 3.0.4...

real    0m0.165s
user    0m0.229s
sys     0m0.029s
Attach success.
Connecting to arthas server... current timestamp is 1538018925
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki: https://alibaba.github.io/arthas
version: 3.0.4
pid: **32391**
timestamp: 1538018925528

$ session (e15b8511-961d-4fe6-878e-0268f2487593) is closed because session is inactive for 5 min(s).
Connection closed by foreign host.

**Comment by opensure** [comment]
我也碰到这个问题，每次都是进入第一次选则的进程

**Comment by Hearen** [comment]
> @liukeyu You need to shutdown Arthas in process 32391 and then attach again.

Using `shutdown` indeed can solve the *attaching* issue but it's so **anti-intuitive** and confusing, is it not?

**Comment by hengyunabc** [comment]
#171

**Comment by frank0417** [comment]
我也遇到类似的问题，明明选择的事19，结果进入的确实第一个进程，显示的PID确实是第19进程的PID，但是我查看jvm信息的时候 classpath:确是第一个，哎。。。

**Comment by hengyunabc** [comment]
> 我也遇到类似的问题，明明选择的事19，结果进入的确实第一个进程，显示的PID确实是第19进程的PID，但是我查看jvm信息的时候 classpath:确是第一个，哎。。。

启动过程是，先选择进程 attach，attach成功的话，在目标进程里会启动一个arthas server，侦听3658端口。然后再用telnet去连接 127.0.0.1 3658 。所以如果之前有进程已经在跑arthas server了，就会连接上之前的进程。 先shutdown，再重新attach。
