### ISSUE TITLE
jad命令无法反编译某个 class 文件

### ISSUE THREAD

**Issue by ainishi123** [alibaba/arthas#2756]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* 执行 java -jar arthas-boot.jar
* Arthas 版本: 3.7.1
* 操作系统版本: linux 
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. com.xxxx.module.grouping.assistdataloader路径下有 10 几个类
2. 执行jad com.xxxx.module.grouping.assistdataloader*

### 期望的结果

执行 jad 后，应该吧该包路径下所有的类显示出来

### 实际运行的结果

结果仅显示部分类，后续使用 jad -c指定其他 classloader也未显示出来剩余的类

**Comment by phamdu98** [comment]
I think may be the classes in  com.xxxx.module.grouping.assistdataloader folder, these do not use by any class so that it not show by arthas jad command. 
![image](https://github.com/alibaba/arthas/assets/38994602/0fd2c552-216c-460b-984e-b5ceda1e87ca)

In this example, if I don't use class Test1, or Test2, jad will not show this class for me

**Comment by hengyunabc** [comment]
jad 只会反编译已经加载到内存里的类。
